version: "3"

services:
  nodejs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - mysql

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx-cert:/etc/nginx/cert

volumes:
  mongodb-data:
  mysql-data:
  nginx-cert:
